name: test-cpp
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run cpp
        working-directory: ./cpp
        run: ls
        run: ./set-paths.sh
        run: make fibonacci
        run: ./fibonacci 30
